### ISSUE TITLE
Remove gulpfile.js as it may cause conflict.

### ISSUE THREAD

**Issue by kmod-midori** [HerringtonDarkholme/Pat-Mat#1]
See https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md#370
Gulp can automatically detect coffeescript and require compiler.

**Comment by HerringtonDarkholme** [comment]
Thanks, fixed in [58dfe93a](https://github.com/HerringtonDarkholme/Pat-Mat/commit/58dfe93a0515d67a9beb3a504daafcfc4ecde01f)
